<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><?php echo ucfirst($controller_name); ?> :: <?php echo $action_name; ?></title>
		<link rel="shortcut icon" href="/img/favicon.ico" />
        <link href="/css/my.css" rel="stylesheet" type="text/css" />
        <link href="/css/ku.css" rel="stylesheet" type="text/css" />
		<script charset="UTF-8" src="/javascript/jquery.js" type="text/javascript"></script>
    </head>
    <body><?php
		if ( ! empty($_SESSION['alert']) )
		{
			$bg = array('F99', 'FC9', 'FF9', 'CF9', '9F9', '9FC', '9FF', '9CF', '99F', 'C9F', 'F9F', 'F9C');
			$n = rand(0, 11);
			$style = ' style="background:#' . $bg[$n] . '; text-align:right"'; ?>
			<div<?php echo $style; ?>><?php echo $_SESSION['alert']; ?></div><?php
			unset($_SESSION['alert']);
		} ?>
		<?php View::partial('list_two', false, array('items' => array('setPathes', 'setStrings'), 'controller_name' => $controller_name, 'action_name' => $action_name) ); ?>
		<div id="content"><?php View::content(); ?></div>
    </body>
</html>
