<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><?php echo ucfirst($controller_name); ?> :: <?php echo $action_name; ?></title>
		<link rel="shortcut icon" href="/img/fastbond/favicon.ico" />
		<script charset="UTF-8" src="/javascript/jquery.js" type="text/javascript"></script>
    </head>
    <body><?php
		View::partial('fastbond/alert');
		View::partial('fastbond/voice'); ?>
		<div id="content"><?php View::content(); ?></div>
    </body>
</html>
